version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_2
    working_dir: /var/www
    volumes:
      - ./laravelApp:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel_2

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql_2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin_2
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel_2

volumes:
  db_data:

networks:
  laravel_2:



